// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vifyvyopfdmqdndkhmxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZnl2eW9wZmRtcWRuZGtobXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjM5NTIsImV4cCI6MjA1OTY5OTk1Mn0.zKF1Sv4kPt124NvUnAP__mRAQTVw6rSn3T4on3a7rr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);